apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    uid: P951FEA4DE68E13C5
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: smart-park
      defaultBucket: sensor-data
      tlsSkipVerify: true
    secureJsonData:
      token: smart-park-token-12345
    editable: true
